version: '3.7'

services:
  api:
    build: .
    ports: 
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: "redis:7.0.7-alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis-password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge